id: 3ec212adb48545f2935bf082dbdedd39
title: Toh_106-Unravelling_the_Intent-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-049-001
  eft-text-version: 1.0.4 2021
